### ISSUE TITLE
How to produce unnumbered chapters

### ISSUE THREAD

**Issue by DejanMilicic** [alexeygumirov/pandoc-for-pdf-how-to#1]
With eisvogel template, I was able to use {-} after the title of the chapter to avoid that chapter to be numbered.
However, that does not work with this template.

How to generate PDF where I can have e.g. first chapter ("Preface") without leading number?

**Comment by alexeygumirov** [comment]
I need to check it because I modified LaTeX template in order to make page break after each chapter. Maybe it broke some original template behavior.

**Comment by alexeygumirov** [comment]
If you want to use header attributes - you need just add "+header_attributes" into the SOURCE_FORMAT variable in the script.
I will update the README with this.
Thanks for a tip!

**Comment by alexeygumirov** [comment]
I will close the issue then.
