### ISSUE TITLE
Linking to figure or table number

### ISSUE THREAD

**Issue by alainmuls** [alexeygumirov/pandoc-for-pdf-how-to#3]
Dear Alexey

I really like how you structured the pandoc to pdf. At this moment I have 1 question, I know how to get the label for a figure or a table, but how can I link from the text to the figure or table number?

In my attempts I used the scripts `pandoc-fignos` and `pandoc-tablenos` which I tried to use, but I got errors trying to do it in this way.

Tx/Alain

**Comment by alexeygumirov** [comment]
I did not find any easy way to do it. I looked into different filters written for that but honestly never tried any.
